name: Q1

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Création de Q1_archive_README.md
      run: |
        cp README.md Q1_archive_README.md

    - name: Configure Git
      run: |
        git config user.name "Amaxi76"
        git config user.email "maximilien.lesterlin@etu.univ-lehavre.fr"

    - name: Commit et push des changements
      run: |
        git add Q1_archive_README.md
        git commit -m "Update Q1_archive_README.md"
        git pull --rebase
        git push origin main
