name: Q2

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Création de Q2_archive_README.md
      run: |
        echo "Nom: Maximilien Lesterlin" > Q2_archive_README.md
        echo "Date et Heure d'exécution: $(date '+%Y-%m-%d %H:%M:%S')" >> Q2_archive_README.md
        echo "" >> Q2_archive_README.md
        echo "Contenu de README.md:" >> Q2_archive_README.md
        echo "" >> Q2_archive_README.md
        cat README.md >> Q2_archive_README.md

    - name: Configure Git
      run: |
        git config user.name "Amaxi76"
        git config user.email "maximilien.lesterlin@etu.univ-lehavre.fr"

    - name: ML commit et push
      run: |
        git add Q2_archive_README.md
        git commit -m "Création de Q2_archive_README.md avec date, nom/prénom et contenu de README.md"
        git push origin main
