name: Q5

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Création Q5_archive_date.txt
        run: |
          DATE=$(date +%d-%m-%Y)
          echo "Maximilien Lesterlin" > Q5_archive_$DATE.txt
          echo "Contenu de Q5.java:" >> Q5_archive_$DATE.txt
          cat Q5.java >> Q5_archive_$DATE.txt

      - name: Configure Git
        run: |
          git config user.name "Amaxi76"
          git config user.email "maximilien.lesterlin@etu.univ-lehavre.fr"
          
      - name: Commit et push des changements
        run: |
          git add Q5_archive_*.txt
          git commit -m "Add Q5_archive_date.txt"
          git push
