name: Q6

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Création de Q6_archive_date.txt
        run: |
          DATE=$(date +%d-%m-%Y-%H%M%S)
          echo "Maximilien Lesterlin" > Q6_archive_$DATE.txt
          echo "Contenu de Q6.java:" >> Q6_archive_$DATE.txt
          cat Q6.java >> Q6_archive_$DATE.txt
          echo "Taille de Q6.java:" >> Q6_archive_$DATE.txt
          wc -c Q6.java | awk '{print $1 " caractères"}' >> Q6_archive_$DATE.txt
          wc -l Q6.java | awk '{print $1 " lignes"}' >> Q6_archive_$DATE.txt
          
      - name: Création de Q6_différences.txt
        run: |
          CURRENT=$(ls -t Q6_archive_*.txt | head -n1)
          PREVIOUS=$(ls -t Q6_archive_*.txt | head -n2 | tail -n1)
          if [ -f "$PREVIOUS" ]; then
            diff "$CURRENT" "$PREVIOUS" > Q6_différences.txt || true
          else
            echo "Pas de fichier précédent pour comparer" > Q6_différences.txt
          fi

      - name: Configure Git
        run: |
          git config user.name "Amaxi76"
          git config user.email "maximilien.lesterlin@etu.univ-lehavre.fr"
          
      - name: Commit et push des changements
        run: |
          git add Q6_archive_*.txt Q6_différences.txt
          git commit -m "Add Q6 files"
          git pull --rebase
          git push
